### ISSUE TITLE
Question: metric persistance

### ISSUE THREAD

**Issue by schell** [bitnomial/prometheus#11]
Is there a solution for persisting metrics here? Is it needed? Specifically - if I restart my metrics server, how will that affect my counters? It seems they would be wiped.

**Comment by lukehoersten** [comment]
My understanding is that persistence is handled by the server not the clients. Either way, the current implementation of the client doesn't do anything to persist. Have you found anything in the docs about client persistence?

**Comment by schell** [comment]
Not yet - I'm still ramping up on prometheus in general, but if my naive mental model is correct then when a monotonic counter is scraped by prometheus at a value of 5 and later scraped at a value of 2 (upon resetting the metrics app and accruing new inc counter events), the time series for that counter would display 2 as its current value, when it should display 7. 

That's not confirmed though. I'll find out.

**Comment by lukehoersten** [comment]
Just searching through the prometheus docs, I couldn't find anything specifying the semantics of client-side stats persistence. It would require periodic disk writes which is agains the performance-oriented design.

Also I found the following on the [client implementation docs](https://prometheus.io/docs/instrumenting/writing_clientlibs/#counter):

> Counter is a monotonically increasing counter. It MUST NOT allow the value to decrease, however it MAY be reset to 0 (such as by server restart).

Which seems to imply counter resets to 0 on server restart is typical behavior.

**Comment by schell** [comment]
This use case may be very special but assume I have a metrics server that gets scraped by prometheus. My app workers push metrics out to this server. Sometimes I need to restart the metric server for updates, which in this case resets all counters, gauges and empties all data from any histograms. 

It may be that most uses of client libraries are for measuring individual machines which indeed get restarted often, hence allowing counts to zero out. In the above case these are long-lived metrics without another datastore behind them, so maybe this is too special.
