### ISSUE TITLE
Consider listing the package in Stackage

### ISSUE THREAD

**Issue by ruuda** [bitnomial/prometheus#12]
The `prometheus` package is currently not in Stackage. [Please consider adding it](https://github.com/commercialhaskell/stackage/blob/619aab53111b21ad7c8e65a872488d0b8dbad32b/MAINTAINERS.md#adding-a-package). It is recommended that the package author maintains the Stackage listing, but if you have no interest in maintaining the Stackage listing, I can volunteer to do so on your behalf.

**Comment by lukehoersten** [comment]
Thanks for the note and offer. I'll investigate and get back to you.

**Comment by lukehoersten** [comment]
I've released v 2.0 of the library to coincide with the Prometheus 2.0 release and I've [submitted to Stackage](https://github.com/commercialhaskell/stackage/pull/3855).

**Comment by ruuda** [comment]
Thanks a lot!

**Comment by kamek-pf** [comment]
Sorry for bumping an old issue, but it appears this package is missing from [recent](https://www.stackage.org/lts-16.5) stackage releases, would it be possible to submit it again ?

**Comment by wraithm** [comment]
@kamek-pf I'll look into this.

**Comment by wraithm** [comment]
@kamek-pf 

I've got a pull request to put this back into stackage.

https://github.com/commercialhaskell/stackage/pull/5555

**Comment by wraithm** [comment]
Okay, it's merged in. It should start showing up in stackage nightly.

**Comment by kamek-pf** [comment]
Thanks a lot @wraithm !
