### ISSUE TITLE
Bump base build dep?

### ISSUE THREAD

**Issue by TomMD** [bitnomial/prometheus#22]
Could we get the base build dep bumped?

**Comment by wraithm** [comment]
Sure, you looking for it to be pushed to hackage? It looks like `build-depends: base           >= 4.7  && < 4.13` that supports the latest base.

**Comment by TomMD** [comment]
Yes, a push to hackage would be useful. Thanks!

**Comment by wraithm** [comment]
@TomMD Okay, 2.1.1 is pushed to hackage. Let me know if everything works.
