### ISSUE TITLE
Label values must be specified up-front (?)

### ISSUE THREAD

**Issue by MaxGabriel** [bitnomial/prometheus#36]
Hi, I was comparing this library to `prometheus-client` and other prometheus libraries. One drawback, as far as I can tell from the API docs, is that all label values must be specified up-front. Is this correct? The documentation gives this as an example, which gives "success" or "failure" for the possible label values:

```
main :: IO ()
main = runRegistryT $ do
    -- Labels can be defined as lists or added to an empty label set
    connectSuccessGauge <- registerGauge "example_connections" (fromList [("login", "success")])
    connectFailureGauge <- registerGauge "example_connections" (addLabel "login" "failure" mempty)
```

This seems somewhat inflexible. For example, the Prometheus docs suggest having an `http_requests_total` with a label for the status code (https://prometheus.io/docs/practices/instrumentation/#use-labels). If you had to specify the status code up front, it seems like you'd have to auto-create values for 100–599, which isn't ideal.

Other libraries don't have this restriction, e.g. https://github.com/prometheus/client_ruby#summary, for comparison

**Comment by wraithm** [comment]
Hi @MaxGabriel,

You’re completely correct that we only support "pre-set labels” at the moment. We’ve not really had a need for dynamic labels yet, but we’d accept a pull request for it. I’d also be willing to work on this when I get some time, but it might take me a bit to get to it. Let me know what you think. I think this would be a fairly straight forward thing to add!

Thanks! Great suggestion.

Best regards,
Matt Wraith

> On Jun 19, 2020, at 11:50, Maximilian Tagher <notifications@github.com> wrote:
> 
> 
> Hi, I was comparing this library to prometheus-client and other prometheus libraries. One drawback, as far as I can tell from the API docs, is that all label values must be specified up-front. Is this correct? The documentation gives this as an example, which gives "success" or "failure" for the possible label values:
> 
> main :: IO ()
> main = runRegistryT $ do
>     -- Labels can be defined as lists or added to an empty label set
>     connectSuccessGauge <- registerGauge "example_connections" (fromList [("login", "success")])
>     connectFailureGauge <- registerGauge "example_connections" (addLabel "login" "failure" mempty)
> 
> This seems somewhat inflexible. For example, the Prometheus docs suggest having an http_requests_total with a label for the status code (https://prometheus.io/docs/practices/instrumentation/#use-labels). If you had to specify the status code up front, it seems like you'd have to auto-create values for 100–599, which isn't ideal.
> 
> Other libraries don't have this restriction, e.g. https://github.com/prometheus/client_ruby#summary, for comparison
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 


-- 


________________________________

Note: This email is for the 
confidential use of the named addressee(s) only and may contain 
proprietary, confidential or privileged information. If you are not the 
intended recipient, you are hereby notified that any review, dissemination 
or copying of this email is strictly prohibited, and to please notify the 
sender immediately and destroy this email and any attachments.

**Comment by wraithm** [comment]
But also, something a bit inefficient you could do for the moment would be to create a map of `Gauge`s where the key is the status code, and the value is the `Gauge` with the appropriate label.

**Comment by MaxGabriel** [comment]
Hey thanks for the quick response. I think I'm going to just use https://hackage.haskell.org/package/prometheus to start and see how it goes. It's not as complete as this package (missing the push capability), and it uses unsafePerformIO, but I wanted to get something working fairly quickly. Might revisit this in the future when we need more capabilities from Prometheus though

**Comment by wraithm** [comment]
@MaxGabriel 

Also, just making it clear, we have the [concurrent registry](https://github.com/bitnomial/prometheus/blob/master/src/System/Metrics/Prometheus/Concurrent/RegistryT.hs). You can register new counters/guages/etc when you encounter them. You don't have to register them all up front. You just have to thread the `RegistryT` through your transformer stack. You could register them on the fly and then put the counters into some other data structure.

Now, we should document this concurrent registry better with examples.

For http codes, I would actually just register them all up front, but that's just me. All of the http error codes that most people care about are known. We were very careful when designing this library to make sure that it was concurrent and performant.

We're actually gonna start working on a wai-middleware-prometheus for exactly this. What do you think? Did you want to start working on this together?

**Comment by lukehoersten** [comment]
Metrics do not need to be registered up-front. They need to be registered in the registryT monad transformer. You can thread that through your monad transformer stack as you see fit. The reason the registryT monad is separate from the metrics is concurrency. You do not want to lock the entire map of metrics just to update a single metric and indeed, a metric may be updated thousands of times between scraper calls which do lock the whole registry. So if you want a separate data structure to keep track of some metrics, maybe a subset, that's up to you. But the metrics are thread safe by themselves with very fast check-and-set concurrency constructs. Making a global map with a global lock would hurt performance and shouldn't be a part of this core library.

**Comment by lukehoersten** [comment]
@MaxGabriel as I mentioned in my previous comment, you can register new metrics, labels, etc. anywhere in your code, not just at startup, by adding the `RegistryT` monad transformer to your transformer stack. This can be done in a thread safe way as well. 

I've also added documentation on the concurrency model:
https://github.com/bitnomial/prometheus/blob/master/README.md#concurrency-model

Please open other issue if needed or continue to comment here if you need additional help.

Thanks for your comments!

**Comment by GambolingPangolin** [comment]
@MaxGabriel 

We just released a new [package for collecting http server metrics][1].  Check it out!  [Here][2] is a usage example.

[1]: http://hackage.haskell.org/package/prometheus-wai-middleware
[2]: https://github.com/bitnomial/prometheus-wai-middleware/blob/master/exec/Main.hs
