### ISSUE TITLE
Can RegistryT be an instance if MonadUnliftIO?

### ISSUE THREAD

**Issue by chrisdone** [bitnomial/prometheus#37]
Monads that are basically ReaderT are typically obvious instances of this class, and it means you can easily thread monad stacks much easier. Would you be open to a PR?

I assume that there’s no reason that actions in RegistryT have to be synchronous.

**Comment by chrisdone** [comment]
Specifically this concurrent one https://github.com/bitnomial/prometheus/blob/master/src/System/Metrics/Prometheus/Concurrent/RegistryT.hs#L21

**Comment by wraithm** [comment]
Interesting! Do you have a use case? It's hard for me to imagine needing unliftIO for some application. I'm not opposed to it, but we've never needed unliftio for anything with this lib.
