### ISSUE TITLE
 Name and label validation

### ISSUE THREAD

**Issue by bergey** [bitnomial/prometheus#40]
How do you want to handle **name and label validation**, mentioned in the README as a wanted feature?  I think the easiest option is to replace invalid characters.  It's probably possible to make them a compile-time failure instead, but I think not worth it.  If that's the approach you want, I can put together a PR to bring https://github.com/Simspace/ekg-prometheus-adapter/commit/704078488730b7e87eaa95ee3bbe3b2ad6cf1cf8 into this package.

**Comment by wraithm** [comment]
That sounds great! Please do.
