### ISSUE TITLE
Please bump upper bound of text dependency on Hackage

### ISSUE THREAD

**Issue by erikd** [bitnomial/prometheus#47]
Here in git you have:
```
               , text            >= 1.2  && < 2.1
```
but the version on Hackage has:
```
text >=1.2 && <1.3,
```
This can be fixed by a metadata update on Hackage.

I am currently using:
```
allow-newer: prometheus:text
```
in my `cabal.project` file

**Comment by wraithm** [comment]
I uploaded 2.2.4 to hackage: https://hackage.haskell.org/package/prometheus-2.2.4
